# Generated by Django 5.1.3 on 2024-11-16 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='aspect',
        ),
        migrations.AddField(
            model_name='rating',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='research.parameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='research',
            name='pdf_document',
            field=models.FileField(upload_to='media/research_pdfs/'),
        ),
    ]
