# Generated by Django 5.1.3 on 2024-11-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_research_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='research',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='research.research'),
            preserve_default=False,
        ),
    ]
