# Generated by Django 5.1.3 on 2024-11-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_rating_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
